apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app.kubernetes.io/name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi
    spec:
      containers:
        - name: fastapi
          image: ghcr.io/example/fastapi:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: base
            - name: LOG_LEVEL
              value: info
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
      restartPolicy: Always
