apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
configMapGenerator: []
