apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fastapi
          image: ghcr.io/example/fastapi:dev
          env:
            - name: ENVIRONMENT
              value: dev
            - name: LOG_LEVEL
              value: debug
