jobs:
  python:
    name: Python Lint & Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # 1) Pythonだけセットアップ（cache指定はしない）
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 2) Poetry を先にインストール
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # 3) Poetry のキャッシュ（lockfile に合わせてキー生成）
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('api/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # 以降は自由に
      - name: Show versions
        run: |
          python --version
          poetry --version

      - name: Install deps
        working-directory: api
        run: poetry install --no-interaction --no-root

      - name: Lint & Test
        working-directory: api
        run: |
          poetry run ruff check .
          poetry run pytest -q
