Python Lint & Test:
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: api

  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: poetry
        cache-dependency-path: api/poetry.lock

    # これを追加（poetry を使う前）
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.2.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install deps
      run: poetry install --no-interaction --no-ansi

    - name: Lint
      run: poetry run ruff check .

    - name: Test
      run: poetry run pytest -q
